name: Deploy with sshpass

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy and restart
        run: |
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} bash --noprofile --norc -s << 'EOF'
            set -e
            REPO_NAME="${{ github.event.repository.name }}"
            REPO_FULL="${{ github.repository }}"

            REPO_DIR=~/deploy/$REPO_NAME
            if [ ! -d "$REPO_DIR" ]; then
              mkdir -p ~/deploy
              cd ~/deploy
              git clone https://github.com/$REPO_FULL.git
            fi
            cd "$REPO_DIR"

            ls
            rm -f .bash_profile

            git pull origin main
            chmod +x restart.bash
            ./restart.bash
          EOF
