name: Deploy with sshpass

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy and restart
        run: |
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} << EOF
            REPO_DIR=~/deploy/${{ github.event.repository.name }}
            if [ ! -d "\$REPO_DIR" ]; then
              mkdir -p ~/deploy
              cd ~/deploy
              git clone https://github.com/${{ github.repository }}.git
            fi
            cd "\$REPO_DIR"
            git pull origin main
            chmod +x restart.bash
            ./restart.bash
          EOF
