name: Deploy with sshpass and send secrets

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy and restart
        run: |
          REPO_NAME="${{ github.event.repository.name }}"
          REPO_FULL="${{ github.repository }}"

          sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} bash -c "
            set -e
            curl ipinfo.io/ip

            REPO_DIR=\$HOME/deploy/$REPO_NAME
            if [ ! -d \"\$REPO_DIR\" ]; then
              mkdir -p \$HOME/deploy
              cd \$HOME/deploy
              git clone https://github.com/$REPO_FULL.git
            fi
            cd \"\$REPO_DIR\"
            git pull origin main
            chmod +x restart.bash
            ./restart.bash
          "
